services:
  angular-app:
    build:
      context: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true #make any changes to the code and docker will auto update